/**
 * CURATED+ CORE ENGINE
 * Features: Path Resolver, Progress Sync, Watchlist, Skip Intro, 
 * Brand Previews, Keyboard Nav, Search Indexing, and Auto-Collections.
 */

// --- 1. CONFIGURATION & DATA ---
const CONFIG = {
    basePath: "movies/", // Root folder for your content
    thumbName: "poster.jpg",
    videoName: "video.mp4",
    previewName: "preview.mp4",
    skipIntroThreshold: 95 // Percent at which a movie is considered 'Finished'
};

// This list can be expanded or generated by a script later.
// "we" use the 'id' to find the folder: movies/[id]/...
const library = [
    { id: "nature-01", title: "Morning Forest", genre: "Nature", tags: ["calm", "trees"], introEnd: 12, collection: "Earth Series" },
    { id: "vintage-01", title: "The Silent Street", genre: "Vintage", tags: ["noir", "classic"], collection: "Noir Archive" },
    { id: "scifi-01", title: "Orbital Reach", genre: "Sci-Fi", tags: ["space", "future"], introEnd: 20 },
    { id: "doc-01", title: "Under the Ice", genre: "Docs", tags: ["ocean", "arctic"], collection: "Earth Series" },
    { id: "short-01", title: "The Red Balloon", genre: "Shorts", tags: ["indie", "art"] }
];

// --- 2. STATE MANAGEMENT ---
let watchlist = JSON.parse(localStorage.getItem('watchlist')) || [];
let currentHeroIndex = 0;
let heroTimer;

// --- 3. THE PATH RESOLVER ---
const getPath = (id, type) => {
    const map = {
        thumb: CONFIG.thumbName,
        video: CONFIG.videoName,
        preview: CONFIG.previewName
    };
    return `${CONFIG.basePath}${id}/${map[type]}`;
};

// --- 4. CORE INITIALIZATION ---
const init = () => {
    renderHero();
    refreshUI();
    setupEventListeners();
    setupScrollEffect();
};

// Feature: Global UI Refresh
const refreshUI = (filterQuery = "") => {
    const container = document.getElementById('dynamic-rows');
    container.innerHTML = ""; // Clear for re-render

    // A. Continue Watching (Smart Logic)
    const inProgress = library.filter(m => {
        const p = localStorage.getItem(`progress_${m.id}`);
        return p > 0 && p < CONFIG.skipIntroThreshold;
    });
    if (inProgress.length > 0 && !filterQuery) {
        createRow("Continue Watching", inProgress, container);
    }

    // B. My List
    const myListItems = library.filter(m => watchlist.includes(m.id));
    if (myListItems.length > 0 && !filterQuery) {
        createRow("My List", myListItems, container);
    }

    // C. Categorized Collections & Genres
    const categories = [...new Set(library.map(m => m.genre))];
    categories.forEach(cat => {
        const matches = library.filter(m => 
            (m.genre === cat || m.collection === cat) && 
            (m.title.toLowerCase().includes(filterQuery.toLowerCase()) || 
             m.tags.some(t => t.includes(filterQuery.toLowerCase())))
        );
        if (matches.length > 0) createRow(cat, matches, container);
    });
};

// --- 5. COMPONENT RENDERING ---
const createRow = (title, movies, target) => {
    const row = document.createElement('section');
    row.className = 'row-container';
    row.innerHTML = `
        <h2>${title}</h2>
        <div class="movie-grid">
            ${movies.map(m => createCard(m)).join('')}
        </div>
    `;
    target.appendChild(row);
};

const createCard = (m) => {
    const p = localStorage.getItem(`progress_${m.id}`) || 0;
    const isAdded = watchlist.includes(m.id);
    
    return `
        <div class="movie-card" data-id="${m.id}" tabindex="0" onclick="openPlayer('${m.id}')">
            <img src="${getPath(m.id, 'thumb')}" loading="lazy" onerror="this.src='https://via.placeholder.com/300x168/1a1d29/ffffff?text=${m.title}'">
            <div class="card-btns">
                <button class="main-play-btn">${p > 0 ? 'RESUME' : 'PLAY'}</button>
                <button class="list-btn" onclick="event.stopPropagation(); toggleWatchlist('${m.id}')">
                    ${isAdded ? '✓ LIST' : '+ LIST'}
                </button>
            </div>
            ${p > 0 ? `<div class="progress-container"><div class="progress-fill" style="width:${p}%"></div></div>` : ''}
        </div>
    `;
};

// --- 6. VIDEO PLAYER & PROGRESS SYNC ---
const openPlayer = (id) => {
    const movie = library.find(m => m.id === id);
    const modal = document.getElementById('player-modal');
    const video = document.getElementById('main-video');
    const skipBtn = document.getElementById('skip-intro');

    // Set Meta
    document.getElementById('modal-title').textContent = movie.title;
    video.src = getPath(id, 'video');
    
    // Feature: Global Playback Sync (Resume)
    const savedTime = localStorage.getItem(`time_${id}`) || 0;
    video.currentTime = savedTime;

    modal.style.display = "flex";
    video.play();

    // Feature: Video Progress Engine
    video.ontimeupdate = () => {
        const percent = (video.currentTime / video.duration) * 100;
        localStorage.setItem(`progress_${id}`, percent);
        localStorage.setItem(`time_${id}`, video.currentTime);

        // Feature: Skip Intro Trigger
        if (movie.introEnd && video.currentTime < movie.introEnd) {
            skipBtn.style.display = "block";
            skipBtn.onclick = () => { video.currentTime = movie.introEnd; skipBtn.style.display = "none"; };
        } else {
            skipBtn.style.display = "none";
        }
    };
};

const closePlayer = () => {
    const video = document.getElementById('main-video');
    video.pause();
    document.getElementById('player-modal').style.display = "none";
    refreshUI(); // Update progress bars on home
};

// --- 7. HERO CAROUSEL LOGIC ---
const renderHero = () => {
    const hero = document.getElementById('hero-carousel');
    const items = library.slice(0, 3); // Top 3 for carousel
    const m = items[currentHeroIndex];

    hero.innerHTML = `
        <img src="${getPath(m.id, 'thumb')}" class="hero-img">
        <div class="hero-overlay">
            <h1>${m.title}</h1>
            <p>Experience this featured selection from the ${m.genre} collection.</p>
            <div class="modal-actions">
                <button class="main-play-btn" onclick="openPlayer('${m.id}')">▶ PLAY</button>
                <button class="list-btn" onclick="toggleWatchlist('${m.id}')">
                    ${watchlist.includes(m.id) ? '✓ ON LIST' : '+ MY LIST'}
                </button>
            </div>
        </div>
    `;

    startHeroTimer();
};

const startHeroTimer = () => {
    clearTimeout(heroTimer);
    heroTimer = setTimeout(() => {
        currentHeroIndex = (currentHeroIndex + 1) % 3;
        renderHero();
    }, 8000);
};

// --- 8. INTERACTIVE FEATURES ---
const toggleWatchlist = (id) => {
    if (watchlist.includes(id)) {
        watchlist = watchlist.filter(item => item !== id);
    } else {
        watchlist.push(id);
    }
    localStorage.setItem('watchlist', JSON.stringify(watchlist));
    refreshUI(document.getElementById('searchInput').value);
};

const setupEventListeners = () => {
    // Search Indexing
    document.getElementById('searchInput').addEventListener('input', (e) => {
        refreshUI(e.target.value);
    });

    // Brand Hover Preview logic
    document.addEventListener('mouseover', (e) => {
        const card = e.target.closest('.movie-card');
        if (card && !card.querySelector('.preview-vid')) {
            const id = card.dataset.id;
            const vid = document.createElement('video');
            vid.src = getPath(id, 'preview');
            vid.className = 'preview-vid'; // Add styling in CSS for this
            vid.muted = true;
            vid.style.position = 'absolute';
            vid.style.top = '0'; vid.style.left = '0'; vid.style.width = '100%';
            vid.style.height = '100%'; vid.style.objectFit = 'cover'; vid.style.zIndex = '-1';
            
            // Wait 500ms before playing to ensure intent
            setTimeout(() => { if (card.contains(vid)) vid.play(); }, 500);
            card.appendChild(vid);
        }
    });

    document.addEventListener('mouseout', (e) => {
        const card = e.target.closest('.movie-card');
        if (card) {
            const vid = card.querySelector('.preview-vid');
            if (vid) vid.remove();
        }
    });
};

const setupScrollEffect = () => {
    window.addEventListener('scroll', () => {
        const topBar = document.querySelector('.top-bar');
        if (window.scrollY > 50) {
            topBar.classList.add('scrolled');
        } else {
            topBar.classList.remove('scrolled');
        }
    });
};

// --- 9. KEYBOARD/TV NAVIGATION ---
window.addEventListener('keydown', (e) => {
    const focusable = document.querySelectorAll('.movie-card, .nav-item, input, button');
    const index = Array.from(focusable).indexOf(document.activeElement);

    if (e.key === "ArrowRight") focusable[index + 1]?.focus();
    if (e.key === "ArrowLeft") focusable[index - 1]?.focus();
    if (e.key === "Enter" && document.activeElement.classList.contains('movie-card')) {
        openPlayer(document.activeElement.dataset.id);
    }
});

// Global assignment for HTML onclicks
window.openPlayer = openPlayer;
window.closePlayer = closePlayer;
window.toggleWatchlist = toggleWatchlist;
window.renderRows = (genre) => {
    document.getElementById('searchInput').value = genre;
    refreshUI(genre);
};

// Kickoff
window.onload = init;
